import { jsPDF } from 'jspdf'

/**
 * Build a real, text-layer PDF of the set list.
 *
 * Unlike the old "open HTML + browser print" approach (which depended on the
 * user's printer choice and could silently produce an image-only PDF via
 * "Microsoft Print to PDF"), this generates the PDF directly with jsPDF, so the
 * output always contains selectable, extractable text — and round-trips cleanly
 * back through the app's PDF importer.
 *
 * @param {{name: string, songs: {title: string, artist?: string}[]}[]} orderedSets
 * @param {string} dateStr
 * @returns {import('jspdf').jsPDF}
 */
export function buildSetListPDF(orderedSets, dateStr) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 40
  const leftX = margin
  const rightX = pageW - margin

  const totalSongs = orderedSets.reduce((n, s) => n + s.songs.length, 0)

  // --- auto-fit: shrink row height / fonts so everything fits on one page ---
  const headerBlock = 58 // title + date + rule
  const footerBlock = 22
  const available = pageH - margin * 2 - headerBlock - footerBlock
  const baseSetHeader = 22
  const baseRow = 18
  const needed = orderedSets.length * baseSetHeader + totalSongs * baseRow
  const scale = needed > available ? Math.max(available / needed, 0.45) : 1
  const setHeaderH = baseSetHeader * scale
  const rowH = baseRow * scale
  const titleFont = 22
  const songFont = Math.max(8, Math.min(13, 13 * scale))
  const setFont = Math.max(9, Math.min(13, 13 * scale))

  let y = margin

  // --- title ---
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(titleFont)
  doc.setTextColor(26, 26, 26)
  doc.text('Set List', pageW / 2, y + titleFont, { align: 'center' })
  y += titleFont + 6

  // --- date ---
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(140, 140, 140)
  doc.text(dateStr, pageW / 2, y, { align: 'center' })
  y += 10

  // --- rule ---
  doc.setDrawColor(60, 60, 60)
  doc.setLineWidth(1.2)
  doc.line(leftX, y, rightX, y)
  y += 14

  let globalNum = 0
  for (const set of orderedSets) {
    // set header bar
    doc.setFillColor(240, 240, 240)
    doc.rect(leftX, y - setHeaderH + 5, rightX - leftX, setHeaderH - 3, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(setFont)
    doc.setTextColor(40, 40, 40)
    doc.text(set.name, leftX + 6, y)
    y += 6

    // song rows
    doc.setFontSize(songFont)
    for (const song of set.songs) {
      globalNum++
      y += rowH
      // number + title as a single left-aligned run (round-trips as one text item)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(26, 26, 26)
      const titleText = `${globalNum}.  ${song.title || ''}`
      doc.text(titleText, leftX + 4, y)
      // artist right-aligned, lighter (separate run; importer rejoins via the big column gap)
      if (song.artist) {
        doc.setTextColor(140, 140, 140)
        doc.text(song.artist, rightX - 4, y, { align: 'right' })
      }
      // faint row separator
      doc.setDrawColor(235, 235, 235)
      doc.setLineWidth(0.5)
      doc.line(leftX, y + rowH * 0.28, rightX, y + rowH * 0.28)
    }
    y += setHeaderH * 0.4
  }

  // --- footer ---
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(190, 190, 190)
  doc.text('Generated by LiveLyrics', pageW / 2, pageH - margin + 4, { align: 'center' })

  return doc
}

/**
 * Build the set-list PDF and download it as a true .pdf file.
 *
 * @param {{name: string, songs: {title: string, artist?: string}[]}[]} orderedSets
 */
export function exportSetListPDF(orderedSets) {
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })
  const doc = buildSetListPDF(orderedSets, dateStr)

  // Download via blob + anchor (works in both browser and the Electron renderer)
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'LiveLyrics-SetList.pdf'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}
